export const CROP_PRESETS = {
  'bawang-merah': {
    name: 'Bawang Merah',
    minTempC: 25,
    maxTempC: 32,
    minHumidity: 50,
    maxHumidity: 70,
    waterNeedMm: 15,
    gddBaseC: 4,
    gddTargetC: 1350,
    pestRiskHumidity: 80,
    pestRiskTempC: 30,
  },
  'bawang-putih': {
    name: 'Bawang Putih',
    minTempC: 15,
    maxTempC: 25,
    minHumidity: 60,
    maxHumidity: 70,
    waterNeedMm: 20,
    gddBaseC: 4,
    gddTargetC: 1850,
    pestRiskHumidity: 80,
    pestRiskTempC: 28,
  },
  'cabai-merah': {
    name: 'Cabai Merah',
    minTempC: 20,
    maxTempC: 30,
    minHumidity: 60,
    maxHumidity: 80,
    waterNeedMm: 25,
    gddBaseC: 10,
    gddTargetC: 1650,
    pestRiskHumidity: 85,
    pestRiskTempC: 28,
  },
  'cabai-rawit': {
    name: 'Cabai Rawit',
    minTempC: 20,
    maxTempC: 30,
    minHumidity: 60,
    maxHumidity: 80,
    waterNeedMm: 25,
    gddBaseC: 10,
    gddTargetC: 1485,
    pestRiskHumidity: 85,
    pestRiskTempC: 28,
  },
} as const;
